import json
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import warnings

warnings.filterwarnings('ignore')
SYSTEM_MESSAGES = {
    "en": {
        "unknown_disease": "unknown",
        "low_confidence": "I couldn't clearly identify your symptoms. Could you describe them using specific words like 'fever', 'chest pain', or 'nausea'?",
        "missing_data": "Disease recognized, but no recommendations are available in the knowledge base yet.",
        "disclaimer": "Note: This advice is generated by AI. Please consult a qualified healthcare provider in Nepal for a real diagnosis."
    },
    "np": {
        "unknown_disease": "अज्ञात",
        "low_confidence": "म तपाईंका लक्षणहरू स्पष्ट रूपमा पहिचान गर्न सकिनँ। कृपया 'ज्वरो', 'छाती दुख्ने', वा 'वाकवाकी' जस्ता विशिष्ट शब्दहरू प्रयोग गरेर वर्णन गर्न सक्नुहुन्छ?",
        "missing_data": "रोग पहिचान भयो, तर डाटाबेसमा यसको लागि कुनै सिफारिसहरू उपलब्ध छैनन्।",
        "disclaimer": "नोट: यो सल्लाह एआई द्वारा उत्पन्न गरिएको हो। वास्तविक निदानको लागि कृपया योग्य चिकित्सकसँग परामर्श लिनुहोस्।"
    }
}

csv_path = r"C:\Users\Acer\Desktop\Coding\MDS_6th_sem\backend\chatbot\data\training_data.csv"
json_path = r"C:\Users\Acer\Desktop\Coding\MDS_6th_sem\backend\chatbot\data\knowledge_base.json"

df = pd.read_csv(csv_path)
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1, 3), sublinear_tf=True, stop_words='english')),
    ('clf', SVC(kernel='linear', C=5.0, class_weight='balanced', probability=True))
])

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['disease'], test_size=0.2, random_state=42)
pipeline.fit(X_train, y_train)
model_accuracy = pipeline.score(X_test, y_test)
print(f"🧠 Brain Initialized! Base Accuracy: {model_accuracy:.2%}")

with open(json_path, encoding='utf-8') as f:
    knowledge_base = json.load(f)

def predict_disease(user_input, lang="en", confidence_threshold=0.45):
    """
    Predicts disease. Requires at least 45% confidence, otherwise triggers a fail-safe.
    """
    probabilities = pipeline.predict_proba([user_input])[0]
    max_confidence = max(probabilities)
    if max_confidence < confidence_threshold:
        return SYSTEM_MESSAGES[lang]["unknown_disease"], max_confidence
    prediction = pipeline.predict([user_input])[0]
    return prediction, max_confidence
def get_recommendations(disease, lang="en"):
    msgs = SYSTEM_MESSAGES.get(lang, SYSTEM_MESSAGES["en"]) 
    if disease in [SYSTEM_MESSAGES["en"]["unknown_disease"], SYSTEM_MESSAGES["np"]["unknown_disease"]]:
        return {
            "error": msgs["low_confidence"],
            "disclaimer": msgs["disclaimer"]
        }
    disease_data = knowledge_base.get(disease.lower(), {})
    lang_data = disease_data.get(lang, disease_data) 

    if lang_data:
        return {
            "disease_name": lang_data.get("display_name", disease.title()),
            "diet": lang_data.get('diet', []),
            "exercise": lang_data.get('exercise', []),
            "tips": lang_data.get('tips', []),
            "when_to_seek_help": lang_data.get('when_to_seek_help', []),
            "disclaimer": msgs["disclaimer"]
        }
        
    return {"error": msgs["missing_data"]}

if __name__ == "__main__":
    print("\n--- Testing English ---")
    test_en, conf_en = predict_disease("I feel weak and have a persistent cough that won't go away", lang="en")
    print(f"Prediction: {test_en} ({conf_en:.2%})")
    print(get_recommendations(test_en, lang="en"))

    print("\n--- Testing Nepali Fallback (Fail-Safe) ---")
    test_np, conf_np = predict_disease("I want to eat momo and pizza", lang="np")
    print(f"Prediction: {test_np} ({conf_np:.2%})")
    print(get_recommendations(test_np, lang="np"))